ALTER TABLE `m400_genryo` CHANGE COLUMN `lf_url` `lf_url` VARCHAR(500) NULL DEFAULT NULL AFTER `path`;
ALTER TABLE `m400_genryo` CHANGE COLUMN `lf_url_dl` `lf_url_dl` VARCHAR(500) NULL DEFAULT NULL COMMENT '2019/07/09' AFTER AFTER `lf_url`;
ALTER TABLE `m400_genryo` CHANGE COLUMN `lf_url_sample` `lf_url_sample` VARCHAR(500) NULL DEFAULT NULL COMMENT '2019/07/09' AFTER `lf_url_dl`;
	